// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_Ydqma6mx2lUsJq0rN_vTyzV8rA7-Oc',
    appId: '1:645806549287:web:ff888ac80853ae8bd965be',
    messagingSenderId: '645806549287',
    projectId: 'pet-shop-7eee2',
    authDomain: 'pet-shop-7eee2.firebaseapp.com',
    storageBucket: 'pet-shop-7eee2.firebasestorage.app',
    measurementId: 'G-VNDWM1ZSGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_Ydqma6mx2lUsJq0rN_vTyzV8rA7-Oc',
    appId: '1:645806549287:android:543bf33156a5fe8aa36102',
    messagingSenderId: '645806549287',
    projectId: 'pet-shop-7eee2',
    storageBucket: 'pet-shop-7eee2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX_Ydqma6mx2lUsJq0rN_vTyzV8rA7-Oc',
    appId: '1:645806549287:web:e8f929acf93c91d0d965be',
    messagingSenderId: '645806549287',
    projectId: 'pet-shop-7eee2',
    authDomain: 'pet-shop-7eee2.firebaseapp.com',
    storageBucket: 'pet-shop-7eee2.firebasestorage.app',
    measurementId: 'G-JNBB4SSN8R',
  );
}
